# Generated by Django 5.1 on 2024-09-02 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=120, null=True)),
                ('last_name', models.CharField(blank=True, max_length=120, null=True)),
                ('email', models.EmailField(max_length=150, null=True)),
                ('grade', models.PositiveSmallIntegerField(default=0, null=True)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
    ]
