# Generated by Django 5.1 on 2024-09-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='birth_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='email',
            field=models.EmailField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='first_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='last_name',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
