# Generated by Django 5.1 on 2024-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teachers', '0002_teachers_birth_date_teachers_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teachers',
            name='address',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='teachers',
            name='phone_number',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
