# Generated by Django 5.1 on 2024-09-02 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(default=1, null=True)),
                ('group_leader', models.CharField(blank=True, max_length=120, null=True)),
                ('average_score', models.PositiveIntegerField(default=1, null=True)),
                ('count_students', models.PositiveIntegerField(default=1, null=True)),
                ('count_subject', models.PositiveIntegerField(default=1, null=True)),
                ('average_age', models.PositiveIntegerField(default=1, null=True)),
            ],
        ),
    ]
